export const ALL_ROOMS_SUCESS = 'ALL_ROOMS_SUCESS';
export const ALL_ROOMS_FAILURE = 'ALL_ROOMS_FAILURE';

export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS';
export const ROOM_DETAILS_FAILURE = 'ROOM_DETAILS_FAILURE';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';